/**
 * Wilson Health Care — Watch products-tripled.xlsx → Auto-update data.js
 * Run: npm run excel:watch
 *
 * Watches products-tripled.xlsx. Every time you Ctrl+S in Excel,
 * this script reads the rows and regenerates data.js automatically.
 *
 * Keep this terminal OPEN while editing in Excel.
 * Press Ctrl+C to stop.
 */

import path from 'path';
import fs from 'fs';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const XLSX = require('xlsx');
const chokidar = require('chokidar');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const XLS = path.join(ROOT, 'products-tripled.xlsx');
const DATA_JS = path.join(ROOT, 'data.js');

// ─── Read Excel → product array ───────────────────────────────────────────
function readExcel() {
    const wb = XLSX.readFile(XLS);
    const ws = wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(ws, { defval: '' });

    return rows.map(row => {
        const id = row['ID'] || row['id'] || Date.now();
        const price = parseFloat(row['Price (Rs)'] || row['price'] || 0) || 0;
        const oldP = parseFloat(row['Old Price (Rs)'] || row['oldPrice'] || 0) || 0;
        const gst = parseFloat(row['GST (%)'] || row['gst'] || 0) || 0;

        const obj = {
            id: isNaN(Number(id)) ? id : Number(id),
            name: String(row['Name'] || row['name'] || '').trim(),
            category: String(row['Category'] || row['category'] || '').trim(),
            price,
            oldPrice: oldP || Math.round(price * 1.3),
            gst,
            discount: String(row['Discount'] || row['discount'] || '').trim(),
            rating: String(row['Rating'] || row['rating'] || '4.0').trim(),
            ratingCount: parseInt(row['Rating Count'] || row['ratingCount'] || 50) || 50,
            tag: String(row['Tag'] || row['tag'] || '').trim(),
            desc: String(row['Description'] || row['desc'] || '').trim(),
            image: String(row['Image URL'] || row['image'] || 'logo.jpg').trim(),
        };

        const usage = String(row['Usage'] || '').trim();
        const extras = String(row['Extra Images'] || '').trim();
        if (usage) obj.usage = usage;
        if (extras) obj.images = extras.split('|').map(s => s.trim()).filter(Boolean);

        return obj;
    });
}

// ─── Build data.js content ─────────────────────────────────────────────────
function generateDataJs(products) {
    const ts = new Date().toLocaleString('en-IN', { hour12: true });

    const lines = products.map(p => {
        const f = [
            `id: ${JSON.stringify(p.id)}`,
            `name: ${JSON.stringify(p.name)}`,
            `category: ${JSON.stringify(p.category)}`,
            `price: ${p.price}`,
            `oldPrice: ${p.oldPrice}`,
            `gst: ${p.gst}`,
            `discount: ${JSON.stringify(p.discount)}`,
            `rating: ${JSON.stringify(p.rating)}`,
            `ratingCount: ${p.ratingCount}`,
            `tag: ${JSON.stringify(p.tag)}`,
            `desc: ${JSON.stringify(p.desc)}`,
            `image: ${JSON.stringify(p.image)}`,
            p.usage ? `usage: ${JSON.stringify(p.usage)}` : null,
            p.images ? `images: ${JSON.stringify(p.images)}` : null,
        ].filter(Boolean).join(',\n        ');
        return `    {\n        ${f}\n    }`;
    });

    return (
        `// Wilson Health Care — Product Data\n` +
        `// Auto-generated from products.xlsx on ${ts}\n` +
        `// Total: ${products.length} products\n` +
        `// DO NOT EDIT THIS FILE — edit products.xlsx then save to update.\n\n` +
        `const products = [\n` +
        lines.join(',\n') +
        `\n];\n`
    );
}

// ─── Sync ─────────────────────────────────────────────────────────────────
let timer = null;

function sync() {
    clearTimeout(timer);
    timer = setTimeout(() => {
        try {
            process.stdout.write(`\r[${new Date().toLocaleTimeString()}] Syncing …`);
            const products = readExcel();

            if (products.length === 0) {
                console.log('\nExcel sheet appears empty — skipping to avoid data loss.');
                return;
            }

            const code = generateDataJs(products);
            fs.writeFileSync(DATA_JS, code, 'utf8');
            console.log(`\r✅ [${new Date().toLocaleTimeString()}] data.js updated — ${products.length} products synced!   `);
        } catch (err) {
            console.log('\n❌ Sync error: ' + err.message);
            console.log('   Tip: Make sure you saved the file from Excel (not a temp lock file).');
        }
    }, 900);
}

// ─── Start ────────────────────────────────────────────────────────────────
if (!fs.existsSync(XLS)) {
    console.error('products-tripled.xlsx not found!');
    console.error('Run first:  npm run excel:triple');
    process.exit(1);
}

console.log('=========================================');
console.log('  Wilson Health Care — Excel Sync Watch  ');
console.log('=========================================');
console.log(`Watching : ${XLS}`);
console.log(`Output   : ${DATA_JS}`);
console.log('');
console.log('Instructions:');
console.log('  1. Open products-tripled.xlsx in Microsoft Excel');
console.log('  2. Edit any product (name, price, discount, image, etc.)');
console.log('  3. Press Ctrl+S in Excel to save');
console.log('  4. Watch this terminal — data.js updates in < 1 second!');
console.log('');
console.log('Press Ctrl+C to stop watching.');
console.log('-----------------------------------------');

const watcher = chokidar.watch(XLS, {
    persistent: true,
    awaitWriteFinish: {
        stabilityThreshold: 600,
        pollInterval: 100,
    },
});

watcher
    .on('ready', () => { console.log('Watcher ready.\n'); sync(); })
    .on('change', () => sync())
    .on('error', e => console.error('Watcher error:', e));
